### ISSUE TITLE
Cannot convert example from YAML to UCL using ucl_tool

### ISSUE THREAD

**Issue by oxr463** [vstakhov/libucl#264]
I took the example UCL and saved it to a `test.ucl` file:

```
param = value;
section {
    param = value;
    param1 = value1;
    flag = true;
    number = 10k;
    time = 0.2s;
    string = "something";
    subsection {
        host = {
            host = "hostname";
            port = 900;
        }
        host = {
            host = "hostname";
            port = 901;
        }
    }
}
```

Then I ran this command to convert to YAML:

```
ucl_tool -i ./test.ucl -o test.yml --format yaml
```
This gave me the following file:

```
param: "value"
section: {
    param: "value",
    param1: "value1",
    flag: true,
    number: 10000,
    time: 0.200000,
    string: "something",
    subsection: {
        host: [
            {
                host: "hostname",
                port: 900
            },
            {
                host: "hostname",
                port: 901
            }
        ]
    }
}
```

I ran this through www.yamllint.com which gave me this:

```
--- 
param: value
section: 
  flag: true
  number: 10000
  param: value
  param1: value1
  string: something
  subsection: 
    host: 
      - 
        host: hostname
        port: 900
      - 
        host: hostname
        port: 901
  time: 0.2
```

I replaced the contents of the `test.yml` file with this ran it back through `ucl_tool` via this command which is failing:

```
ucl_tool -i ./test.yml -o ./test.ucl
Failed to parse input file: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '-'
```

Reference(s):
- https://github.com/vstakhov/libucl#basic-structure
